#!/bin/bash
#if u need makewords for linux, it's here (same as origin unix's promotional video): https://github.com/alexzk1/makewords
function process {
  cat $1 | makewords | sort | while read -r line; do echo "{NID}\"$line\"{NID}  { return LexerScheme::StyleType::KEYWORD; }"; done > $2
  
}


process gl_words.txt lex_gl.txt

#cat gl_words.txt | makewords | sort | while read -r line; do echo "{NID}\"$line\"{NID}  { return LexerScheme::StyleType::KEYWORD; }"; done > lex_gl.txt
#cat js_words.txt | makewords | sort | while read -r line; do echo "{NID}\"$line\"{NID}  { return LexerScheme::StyleType::KEYWORD; }"; done > lex_js.txt

